### ISSUE TITLE
Github Token Auth Scope

### ISSUE THREAD

**Issue by chris-s-friedman** [d3b-center/d3b-release-maker#55]
in the readme: 

>If you only want to release public repositories, you don't need to grant the token any authorization scopes. If you want to release private repositories as well, the token needs the "repo" scope.

Does this still hold true?

I just tried using the release maker on a public repo with a github token that i did not grant an authorization scope to and got the error below: 

```sh
Traceback (most recent call last):
  File "/Users/chris/dotfiles/venv/bin/release", line 33, in <module>
    sys.exit(load_entry_point('d3b-release-maker==2.1.0', 'console_scripts', 'release')())
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/d3b_release_maker/cli.py", line 64, in make_release_cmd
    make_release(repo, blurb_file)
  File "/Users/chris/dotfiles/venv/lib/python3.9/site-packages/d3b_release_maker/release_maker.py", line 557, in make_release
    subprocess.run(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'push', '--force', 'origin', 'release-0.1.0-🏷']' returned non-zero exit status 128.
```

After giving the same token repo auth scope, the release worked. 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/17438916/132950732-5f5275e0-2bf7-42a7-99ea-d8ecbbdc5dfe.png">

My guess is that tokens being used to run the release maker on public repositories need - minimally - `repo >> public_repo` authorization.

**Comment by chris-s-friedman** [comment]
After attempting with only having public_repo auth, the release maker works 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/17438916/132951345-f9c69fe2-b2b0-469e-9c67-47350c4d42df.png">

**Comment by fiendish** [comment]
It looks like Github has changed their token security model since that was written. I'll fix the description. Thanks!
